trajectory_planner:
  # goal tolerances
  yaw_goal_tolerance: 0.15
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  # Robot Configuration Parameters
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  acc_lim_theta: 3.2

  max_vel_x: 0.25
  min_vel_x: -0.25

  max_vel_theta: 0.5
  min_vel_theta: -0.5
  min_in_place_vel_theta: 0.4

  # Forward Simulation Parameters
  sim_time: 1.7
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  heading_lookahead: 0.325
  vx_samples: 20
  vtheta_samples: 20
  controller_frequency: 10.0

  # Robot Footprint
  # set for turtlebot3 waffle pi ( the other turtle bots are smaller)
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: "polygon"
    radius: 0.2 # for type "circular"
    vertices: [[-0.30, -0.30], [-0.30, 0.30], [0.30, 0.30], [0.30, -0.30]] # for type "polygon"
    padding: 0.01

  # Cost Weights
  pdist_scale: 0.6 # higher weight make the stick to global path
  gdist_scale: 0.8
  occdist_scale: 0.01

  oscillation_reset_dist: 0.05
  escape_reset_dist: 0.10
  escape_reset_theta: 1.57079632679


  # Differential-drive robot configuration
  holonomic_robot: true

  escape_vel: -0.1

  dwa: false
  heading_scoring: false
  heading_scoring_timestep: 0.1

  simple_attractor: false

  y_vels: [-0.3, -0.1, 0.1, 0.3]
